/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/litfass.glb -o src/components/Litfass.jsx -r public 
*/

import React from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'

export function Litfass(props) {
  const texture = useTexture("/flyers/project1.png");
  const { nodes, materials } = useGLTF('/models/litfass.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Litfass_Material.001']} />
      <mesh geometry={nodes.Cylinder006_1.geometry} >
        <meshBasicMaterial transparent opacity={0} />
        <Decal
            debug // Makes "bounding box" of the decal visible
            position={[0, 1.8, 1]} // Position of the decal
            rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
            scale={[1.5, 1.5, 1.5]} // Scale of the decal
          >
            <meshStandardMaterial
              map={texture}
              polygonOffset
              polygonOffsetFactor={-1} // The mesh should take precedence over the original
            />
          </Decal>
        </mesh>
    </group>
  )
}

useGLTF.preload('/models/litfass.glb')
